use_frameworks!

platform :ios, '9.0'

target 'HKAlertController_Example' do
  pod 'HKAlertController', :path => '../'

  target 'HKAlertController_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
